joint_ids_map:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
step_dt: 0.02
stiffness:
  - 25.0
  - 25.0
  - 25.0
  - 25.0
  - 25.0
  - 25.0
  - 25.0
  - 25.0
  - 25.0
  - 25.0
  - 25.0
  - 25.0
damping:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
default_joint_pos:
  - 0.1
  - -0.1
  - 0.1
  - -0.1
  - 0.8
  - 0.8
  - 1.0
  - 1.0
  - -1.5
  - -1.5
  - -1.5
  - -1.5
commands:
  base_velocity:
    default:
      - 0.5
      - 0.0
      - 0.0
    ranges:
      lin_vel_x:
        - -0.8
        - 0.8
      lin_vel_y:
        - -0.3
        - 0.3
      ang_vel_z:
        - -0.6
        - 0.6
actions:
  JointPositionAction:
    joint_names:
      - FL_hip_joint
      - FR_hip_joint
      - RL_hip_joint
      - RR_hip_joint
      - FL_thigh_joint
      - FR_thigh_joint
      - RL_thigh_joint
      - RR_thigh_joint
      - FL_calf_joint
      - FR_calf_joint
      - RL_calf_joint
      - RR_calf_joint
    joint_ids:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
    scale:
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
    offset:
      - 0.1
      - -0.1
      - 0.1
      - -0.1
      - 0.8
      - 0.8
      - 1.0
      - 1.0
      - -1.5
      - -1.5
      - -1.5
      - -1.5
    clip:
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
      -
        - -100.0
        - 100.0
observations:
  policy_order:
    -
      name: base_ang_vel
      dim: 3
      history_length: 1
      scale:
        - 1.0
        - 1.0
        - 1.0
    -
      name: projected_gravity
      dim: 3
      history_length: 1
      scale:
        - 1.0
        - 1.0
        - 1.0
    -
      name: velocity_commands
      dim: 3
      history_length: 1
      scale:
        - 1.0
        - 1.0
        - 1.0
    -
      name: joint_pos_rel
      dim: 12
      history_length: 1
      scale:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
    -
      name: joint_vel_rel
      dim: 12
      history_length: 1
      scale:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
    -
      name: last_action
      dim: 12
      history_length: 1
      scale:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
  policy_dim: 45
  policy_history_length: 100
  policy_history_dim: 4500
  policy_kind: blind_history_policy
